#!/usr/local/bin/perl

use 5.010;
use strict;
use warnings;

use Getopt::Std;
use iOS::Activator::Listener::Create qw< activator_listener >;

my $opt = {};
getopts('c:r',$opt);

print activator_listener($opt);

